Section "Device"
    Identifier "SJAgent SPI Framebuffer"
    Driver "fbdev"
    Option "fbdev" "/dev/fb0"
EndSection

Section "Monitor"
    Identifier "SJAgent SPI Monitor"
EndSection

Section "Screen"
    Identifier "SJAgent SPI Screen"
    Device "SJAgent SPI Framebuffer"
    Monitor "SJAgent SPI Monitor"
    DefaultDepth 16
    SubSection "Display"
        Depth 16
        Modes "480x320"
    EndSubSection
EndSection

Section "ServerLayout"
    Identifier "SJAgent SPI Layout"
    Screen "SJAgent SPI Screen"
EndSection
