-- Product catalog schema owned by sjagent_core.
-- This file is schema-only; product data import is handled by scripts/migrate_product_catalog.py.

CREATE TABLE IF NOT EXISTS product_unit (
    id BIGINT UNSIGNED NOT NULL,
    name VARCHAR(30) NOT NULL,
    code VARCHAR(30) NOT NULL,
    unit_type VARCHAR(30) NOT NULL,
    precision_scale TINYINT NOT NULL DEFAULT 0,
    is_enabled TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_product_unit_code (code),
    UNIQUE KEY uk_product_unit_name (name)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_category (
    id BIGINT UNSIGNED NOT NULL,
    parent_id BIGINT UNSIGNED NULL,
    code VARCHAR(80) NULL,
    name VARCHAR(80) NOT NULL,
    product_type VARCHAR(30) NOT NULL,
    inventory_policy VARCHAR(20) NULL,
    default_unit_id BIGINT UNSIGNED NULL,
    sort_order INT NULL,
    is_enabled TINYINT NOT NULL DEFAULT 1,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_product_category_parent (parent_id),
    KEY idx_product_category_type (product_type),
    UNIQUE KEY uk_product_category_code (code)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_spu (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    title VARCHAR(160) NOT NULL,
    product_type VARCHAR(30) NOT NULL,
    series VARCHAR(80) NULL,
    size_label VARCHAR(80) NULL,
    available_colors JSON NULL,
    tea_type VARCHAR(80) NULL,
    case_unit_id BIGINT UNSIGNED NULL,
    case_pack_qty DECIMAL(12,3) NULL,
    default_category_id BIGINT UNSIGNED NULL,
    default_supplier_id BIGINT UNSIGNED NULL,
    inventory_policy VARCHAR(20) NOT NULL DEFAULT 'strict',
    purchase_policy VARCHAR(30) NOT NULL DEFAULT 'order_qty',
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    sort_order INT NULL,
    note TEXT NULL,
    source VARCHAR(30) NOT NULL DEFAULT 'manual',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    KEY idx_product_spu_type (product_type),
    KEY idx_product_spu_series (series),
    KEY idx_product_spu_category (default_category_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_sku (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    spu_id BIGINT UNSIGNED NOT NULL,
    sku_no VARCHAR(80) NOT NULL,
    primary_category_id BIGINT UNSIGNED NULL,
    category_ids JSON NULL,
    color VARCHAR(60) NULL,
    bag_type VARCHAR(40) NULL,
    tea_type VARCHAR(80) NULL,
    material_type VARCHAR(80) NULL,
    service_type VARCHAR(80) NULL,
    unit_id BIGINT UNSIGNED NOT NULL,
    min_purchase_qty DECIMAL(12,3) NULL,
    min_purchase_unit_id BIGINT UNSIGNED NULL,
    inventory_policy VARCHAR(20) NOT NULL DEFAULT 'strict',
    purchase_policy VARCHAR(30) NOT NULL DEFAULT 'order_qty',
    default_warehouse_id BIGINT UNSIGNED NULL,
    default_supplier_id BIGINT UNSIGNED NULL,
    retail_price DECIMAL(12,2) NULL,
    min_price DECIMAL(12,2) NULL,
    max_price DECIMAL(12,2) NULL,
    cost_price DECIMAL(12,2) NULL,
    price_note VARCHAR(255) NULL,
    is_stock_item TINYINT NOT NULL DEFAULT 1,
    is_sellable TINYINT NOT NULL DEFAULT 1,
    is_listed TINYINT NOT NULL DEFAULT 0,
    status VARCHAR(20) NOT NULL DEFAULT 'active',
    main_image_url VARCHAR(500) NULL,
    detail_image_urls JSON NULL,
    content_html MEDIUMTEXT NULL,
    search_text TEXT NULL,
    source VARCHAR(30) NOT NULL DEFAULT 'manual',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    deleted_at DATETIME NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_product_sku_no (sku_no),
    KEY idx_product_sku_spu (spu_id),
    KEY idx_product_sku_category (primary_category_id),
    KEY idx_product_sku_color (color),
    KEY idx_product_sku_status (status)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_alias (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    target_type VARCHAR(20) NOT NULL,
    target_id BIGINT UNSIGNED NOT NULL,
    alias VARCHAR(160) NOT NULL,
    normalized_alias VARCHAR(160) NOT NULL,
    alias_type VARCHAR(30) NOT NULL,
    weight INT NOT NULL DEFAULT 10,
    is_enabled TINYINT NOT NULL DEFAULT 1,
    source VARCHAR(30) NOT NULL DEFAULT 'manual',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_product_alias (target_type, target_id, normalized_alias, alias_type),
    KEY idx_product_alias_normalized (normalized_alias)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS product_media (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    sku_id BIGINT UNSIGNED NULL,
    spu_id BIGINT UNSIGNED NULL,
    media_type VARCHAR(30) NOT NULL,
    url VARCHAR(500) NOT NULL,
    storage VARCHAR(30) NOT NULL,
    path VARCHAR(500) NULL,
    file_name VARCHAR(255) NULL,
    mime_type VARCHAR(80) NULL,
    width INT NULL,
    height INT NULL,
    sha256 CHAR(64) NULL,
    sort_order INT NOT NULL DEFAULT 0,
    is_active TINYINT NOT NULL DEFAULT 1,
    source VARCHAR(30) NOT NULL DEFAULT 'manual',
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    KEY idx_product_media_sku (sku_id),
    KEY idx_product_media_spu (spu_id),
    KEY idx_product_media_type (media_type)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;

CREATE TABLE IF NOT EXISTS migration_product_ref (
    id BIGINT UNSIGNED NOT NULL AUTO_INCREMENT,
    entity_type VARCHAR(20) NOT NULL,
    native_id BIGINT UNSIGNED NOT NULL,
    source_table VARCHAR(120) NOT NULL,
    external_id VARCHAR(120) NOT NULL,
    external_key VARCHAR(160) NULL,
    created_at DATETIME NOT NULL,
    updated_at DATETIME NOT NULL,
    PRIMARY KEY (id),
    UNIQUE KEY uk_migration_product_ref (entity_type, source_table, external_id),
    KEY idx_migration_product_ref_native (entity_type, native_id)
) ENGINE=InnoDB DEFAULT CHARSET=utf8mb4 COLLATE=utf8mb4_unicode_ci;
